version: '3.1'

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik
      - $PWD/config/traefik.yml:/etc/traefik/traefik.yml:ro

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    depends_on:
      - db

volumes:
  db_data:
  traefik_config: