version: '3.1'

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik
      - $PWD/config/traefik.yml:/etc/traefik/traefik.yml:ro

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`adminer.elvisdiniz.com`)'
      - 'traefik.http.routers.adminer.entrypoints=websecure'
      - 'traefik.http.routers.adminer.tls=true'
      - 'traefik.http.routers.adminer.tls.certresolver=production'
    depends_on:
      - db

  ha-casa:
    image: linuxserver/openssh-server:latest
    restart: unless-stopped
    ports:
      - 2222:2222  # External SSH port, to be used with autossh by homeassistant
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - USER_NAME=homeassistant
      - PASSWORD_ACCESS=false
      - SUDO_ACCESS=false
      - PUBLIC_KEY_FILE=/authorized_keys
    volumes:
      - ./ha-casa/openssh_config:/config  # Enable AllowTcpForwarding and GatewayPorts after creation during first run
      - ./ha-casa/authorized_keys:/authorized_keys:ro  # Store the generated ssh key here
    labels:
      traefik.enable: "true"
      traefik.http.routers.ha-casa.rule: Host(`ha-casa.elvisdiniz.com`)
      traefik.http.routers.ha-casa.tls.certresolver: production
      traefik.http.routers.ha-casa.service: ha-casa
      traefik.http.services.ha-casa.loadbalancer.server.port: 8001

  db_backup:
    image: databack/mysql-backup:latest
    environment:
      DB_SERVER: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER:-root}
      DB_PASS: ${MYSQL_ROOT_PASSWORD}
      DB_DUMP_FREQ: ${DB_DUMP_FREQ:-1440}
      DB_DUMP_BEGIN: ${DB_DUMP_BEGIN:-+4}
      COMPRESSION: ${COMPRESSION:-bzip2}
      DB_DUMP_SAFECHARS: "1"
      DB_DUMP_TARGET: s3://${AWS_BUCKET_NAME}/drax-db-backup
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    depends_on:
      - db

volumes:
  db_data:
  traefik_config:
