version: "3"

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_config:/etc/traefik
      - $PWD/config/traefik.yml:/etc/traefik/traefik.yml:ro

volumes:
  traefik_config:

networks:
  traefik_public:
    external: true