version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula

volumes:
  db_data: