version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`adminer.elvisdiniz.com`)'
      - 'traefik.http.routers.adminer.entrypoints=websecure'
      - 'traefik.http.routers.adminer.tls=true'
      - 'traefik.http.routers.adminer.tls.certresolver=staging'
    depends_on:
      - db

volumes:
  db_data:
